repos:
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.2
    hooks:
    - id: isort
      args: [--filter-files, --profile=black]
      files: \.py$
