repos:
  - repo: local
    hooks:

    - id: black
      name: black
      entry: poetry run black .
      language: python
      language_version: python3
      types:
        - file
        - python

    - id: isort
      name: isort
      entry: poetry run isort --profile=black .
      language: system
      pass_filenames: false
      types:
        - file
        - python
